name: 'Flutter Package Caching Action'
description: 'Cache package dependencies and generated files for Flutter'
inputs:
  fail-on-cache-miss:
    description: 'Fail the workflow if cache entry is not found'
    default: 'false'
    required: false
  enableCrossOsArchive:
    description: 'An optional boolean when enabled, allows windows runners to restore caches that were saved on other platforms'
    default: 'false'
    required: false
  lookup-only:
    description: 'Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache'
    default: 'false'
    required: false
outputs:
  cache-hit:
    description: "A boolean value to indicate cache has been found for both package dependencies and generated code."
    value: ${{ steps.pub-cache.outputs.cache-hit && steps.generator-cache.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - uses: ilovelinux/flutter-cache-action/pub/get@v1
      id: pub-cache
      with:
        fail-on-cache-miss: ${{ github.event.inputs.fail-on-cache-miss }}
        enableCrossOsArchive: ${{ github.event.inputs.enableCrossOsArchive }}
        lookup-only: ${{ github.event.inputs.lookup-only }}
    - uses: ilovelinux/flutter-cache-action/build_runner/generate@v1
      id: generator-cache
      with:
        fail-on-cache-miss: ${{ github.event.inputs.fail-on-cache-miss }}
        enableCrossOsArchive: ${{ github.event.inputs.enableCrossOsArchive }}
        lookup-only: ${{ github.event.inputs.lookup-only }}
