name: 'Flutter Package Caching Action'
description: 'Cache package dependencies'
inputs:
  key:
    description: 'An exact string match for the key. The key is used to create a unique identifier for the cache entry.'
    required: false
    default: flutter-pub-cache-${{ hashFiles('**/pubspec.lock') }}
  pub-cache-path:
    description: 'The path to the pub-cache directory (default: env.PUB_CACHE))'
    default: ''
    required: false
  enableCrossOsArchive:
    description: 'An optional boolean when enabled, allows windows runners to restore caches that were saved on other platforms'
    default: 'false'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/cache/save@v3
      with:
        path: ${{ inputs.pub-cache-path || env.PUB_CACHE }}
        key: ${{ inputs.key }}
        enableCrossOsArchive: ${{ inputs.enableCrossOsArchive }}
