name: 'Flutter Package Caching Action'
description: 'Cache package dependencies'
inputs:
  enableCrossOsArchive:
    description: 'An optional boolean when enabled, allows windows runners to restore caches that were saved on other platforms'
    default: 'false'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/cache/save@v3
      with:
        path: |
          ${{ env.FLUTTER_HOME }}/.pub-cache
          **/.packages
          **/.flutter-plugins
          **/.flutter-plugin-dependencies
          **/.dart_tool/package_config.json
          **/.dart_tool/flutter_gen/pubspec.yaml
        key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
        enableCrossOsArchive: ${{ inputs.enableCrossOsArchive }}
