name: 'Flutter Package Caching Action'
description: 'Cache package dependencies'
inputs:
  key:
    description: 'An optional key to use for restoring and saving the cache'
    required: false
    default: build-runner-${{ hashFiles('**/pubspec.lock', '**/*.dart') }}
  enableCrossOsArchive:
    description: 'An optional boolean when enabled, allows windows runners to restore caches that were saved on other platforms'
    default: 'false'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/cache/save@v3
      with:
        path: |
          **/.dart_tool
          **/*.g.dart
          **/*.freezed.dart
          **/*.mocks.dart
          **/*.config.dart
        key: ${{ inputs.key }}
        enableCrossOsArchive: ${{ inputs.enableCrossOsArchive }}
